import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  env: {
    NEXT_PUBLIC_CIRCLE_WALLET_ID_ETH: process.env.NEXT_PUBLIC_CIRCLE_WALLET_ID_ETH,
    NEXT_PUBLIC_CIRCLE_WALLET_ADDRESS_ETH: process.env.NEXT_PUBLIC_CIRCLE_WALLET_ADDRESS_ETH,
    NEXT_PUBLIC_CIRCLE_WALLET_ID_POLYGON: process.env.NEXT_PUBLIC_CIRCLE_WALLET_ID_POLYGON,
    NEXT_PUBLIC_CIRCLE_WALLET_ADDRESS_POLYGON: process.env.NEXT_PUBLIC_CIRCLE_WALLET_ADDRESS_POLYGON,
    NEXT_PUBLIC_CIRCLE_WALLET_ID_ARC: process.env.NEXT_PUBLIC_CIRCLE_WALLET_ID_ARC,
    NEXT_PUBLIC_CIRCLE_WALLET_ADDRESS_ARC: process.env.NEXT_PUBLIC_CIRCLE_WALLET_ADDRESS_ARC,
  },
};

export default nextConfig;
